#!/bin/bash

ACTIVE_WINDOW_ID=$(xprop -root -f _NET_ACTIVE_WINDOW 0x " \$0\\n" _NET_ACTIVE_WINDOW | 
	awk "{print \$2}")
WINDOW_INFO=`xprop -id $ACTIVE_WINDOW_ID | 
	grep WM_NAME\(UTF8_STRING\) | 
	awk -F"= " '{print $2}'`

echo ${WINDOW_INFO:1:-1}
