#!/bin/bash

HOST=127.0.0.1
PORT=6666

${VOLUME=`mpc --host=$HOST --port=$PORT volume`}
${CURRENT_ARTIST=`mpc --host=$HOST --port=$PORT current --format="[%artist%]"`}
${CURRENT_TITLE=`mpc --host=$HOST --port=$PORT current --format="[%title%]"`}
${TIME_LN=`mpc --host=$HOST --port=$PORT status | grep playing`}

IFS=', ' read -a time <<< $TIME_LN

function checklen() {
	local _str=$1
	local _maxLen=$2
	local chrLen=${#_str}
	
	if [ $(( $chrLen )) -gt $(( $_maxLen )) ]
	then		
		local cutChr=$(( $_maxLen-$chrLen ))
		local result="${_str:0:$cutChr}..."
		echo $result
	else
		echo $_str
	fi
}

CURRENT_ARTIST=$(checklen "$CURRENT_ARTIST" 20)
CURRENT_TITLE=$(checklen "$CURRENT_TITLE" 30)

if  [ -z "$CURRENT_ARTIST" ]&&[ -z "$CURRENT_TITLE" ]
then
	echo "MPD      STOPPED       ${VOLUME:7}"
elif [ "${time[2]}" = '' ]
then
	echo "$CURRENT_ARTIST - $CURRENT_TITLE      PAUSED       ${VOLUME:7}"
else
	echo "$CURRENT_ARTIST - $CURRENT_TITLE      ${time[2]}       ${VOLUME:7}"
fi


